Show an error when parsing fails

diff --git a/scripts/bash-include b/scripts/bash-include
--- a/scripts/bash-include
+++ b/scripts/bash-include
@@ -41,7 +41,13 @@ export PNPM_STORE_DIR="$CACHE_DIR/pnpm-store"
 # Extract some values from the FIREBASE environment variable.
 if [[ ! -z $FIREBASE ]]; then
 	export FIREBASE_PROJECT="$(echo $FIREBASE | sed 's/\\n/ /g; s/\\t/ /g' | jq -r .projectId)"
+	if [[ $? -ne 0 ]]; then
+    	echo "bash-include: Error: Failed to parse 'projectId' from FIREBASE environment variable"
+	fi
 	export FIREBASE_AUTH_DOMAIN="$(echo $FIREBASE | sed 's/\\n/ /g; s/\\t/ /g' | jq -r .authDomain)"
+	if [[ $? -ne 0 ]]; then
+		echo "bash-include: Error: Failed to parse 'authDomain' from FIREBASE environment variable"
+	fi
 fi
 
 # Configure gcloud as best we can.
@@ -49,7 +55,13 @@ export GOOGLE_CLOUD_CONFIG="$HOME/.config/gcloud"
 export GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_CLOUD_CONFIG/application_default_credentials.json"
 if [[ ! -z $GOOGLE_CREDENTIALS ]]; then
 	export GOOGLE_PROJECT="$(echo $GOOGLE_CREDENTIALS | sed 's/\\n/ /g; s/\\t/ /g' | jq -r .project_id)"
+	if [[ $? -ne 0 ]]; then
+		echo "bash-include: Error: Failed to parse 'project_id' from GOOGLE_CREDENTIALS environment variable"
+	fi
 	export GOOGLE_ACCOUNT="$(echo $GOOGLE_CREDENTIALS | sed 's/\\n/ /g; s/\\t/ /g' | jq -r .client_email)"
+	if [[ $? -ne 0 ]]; then
+		echo "bash-include: Error: Failed to parse 'client_email' from GOOGLE_CREDENTIALS environment variable"
+	fi
 fi
 
 # Give function discovery a little more time to complete.
